// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: em/authority/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/x/upgrade/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGasPricesRequest struct {
}

func (m *QueryGasPricesRequest) Reset()         { *m = QueryGasPricesRequest{} }
func (m *QueryGasPricesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGasPricesRequest) ProtoMessage()    {}
func (*QueryGasPricesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d766145e8bc7b365, []int{0}
}
func (m *QueryGasPricesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGasPricesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGasPricesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGasPricesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGasPricesRequest.Merge(m, src)
}
func (m *QueryGasPricesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGasPricesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGasPricesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGasPricesRequest proto.InternalMessageInfo

type QueryGasPricesResponse struct {
	MinGasPrices github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,1,rep,name=min_gas_prices,json=minGasPrices,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"min_gas_prices" yaml:"min_gas_prices"`
}

func (m *QueryGasPricesResponse) Reset()      { *m = QueryGasPricesResponse{} }
func (*QueryGasPricesResponse) ProtoMessage() {}
func (*QueryGasPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d766145e8bc7b365, []int{1}
}
func (m *QueryGasPricesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGasPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGasPricesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGasPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGasPricesResponse.Merge(m, src)
}
func (m *QueryGasPricesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGasPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGasPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGasPricesResponse proto.InternalMessageInfo

func (m *QueryGasPricesResponse) GetMinGasPrices() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.MinGasPrices
	}
	return nil
}

type QueryUpgradePlanRequest struct {
}

func (m *QueryUpgradePlanRequest) Reset()         { *m = QueryUpgradePlanRequest{} }
func (m *QueryUpgradePlanRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUpgradePlanRequest) ProtoMessage()    {}
func (*QueryUpgradePlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d766145e8bc7b365, []int{2}
}
func (m *QueryUpgradePlanRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUpgradePlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUpgradePlanRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUpgradePlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUpgradePlanRequest.Merge(m, src)
}
func (m *QueryUpgradePlanRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUpgradePlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUpgradePlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUpgradePlanRequest proto.InternalMessageInfo

type QueryUpgradePlanResponse struct {
	Plan types1.Plan `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan" yaml:"plan"`
}

func (m *QueryUpgradePlanResponse) Reset()         { *m = QueryUpgradePlanResponse{} }
func (m *QueryUpgradePlanResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUpgradePlanResponse) ProtoMessage()    {}
func (*QueryUpgradePlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d766145e8bc7b365, []int{3}
}
func (m *QueryUpgradePlanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUpgradePlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUpgradePlanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUpgradePlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUpgradePlanResponse.Merge(m, src)
}
func (m *QueryUpgradePlanResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUpgradePlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUpgradePlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUpgradePlanResponse proto.InternalMessageInfo

func (m *QueryUpgradePlanResponse) GetPlan() types1.Plan {
	if m != nil {
		return m.Plan
	}
	return types1.Plan{}
}

func init() {
	proto.RegisterType((*QueryGasPricesRequest)(nil), "em.authority.v1.QueryGasPricesRequest")
	proto.RegisterType((*QueryGasPricesResponse)(nil), "em.authority.v1.QueryGasPricesResponse")
	proto.RegisterType((*QueryUpgradePlanRequest)(nil), "em.authority.v1.QueryUpgradePlanRequest")
	proto.RegisterType((*QueryUpgradePlanResponse)(nil), "em.authority.v1.QueryUpgradePlanResponse")
}

func init() { proto.RegisterFile("em/authority/v1/query.proto", fileDescriptor_d766145e8bc7b365) }

var fileDescriptor_d766145e8bc7b365 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x3f, 0x6f, 0xd3, 0x40,
	0x18, 0xc6, 0x7d, 0xa5, 0x20, 0x71, 0x45, 0x20, 0x19, 0x4a, 0x43, 0xa8, 0xec, 0x62, 0x55, 0xb4,
	0x80, 0x72, 0xa7, 0x94, 0xad, 0x63, 0x00, 0xc1, 0xc0, 0x50, 0x22, 0xb1, 0xb0, 0x44, 0x17, 0xe7,
	0xd5, 0xf5, 0x84, 0xef, 0xce, 0xf5, 0x9d, 0x23, 0xbc, 0x22, 0xb1, 0xa2, 0x4a, 0x2c, 0x8c, 0x9d,
	0xd9, 0xf8, 0x16, 0x1d, 0x2b, 0xb1, 0x30, 0x15, 0x94, 0xf0, 0x09, 0xf8, 0x04, 0xc8, 0xf6, 0x39,
	0xa4, 0x6d, 0x24, 0x98, 0x12, 0xeb, 0x79, 0xff, 0xfc, 0x9e, 0xe7, 0x5e, 0x7c, 0x17, 0x24, 0x65,
	0xb9, 0xdd, 0xd7, 0x99, 0xb0, 0x05, 0x1d, 0x77, 0xe9, 0x41, 0x0e, 0x59, 0x41, 0xd2, 0x4c, 0x5b,
	0xed, 0xdf, 0x00, 0x49, 0x66, 0x22, 0x19, 0x77, 0xdb, 0xb7, 0xb8, 0xe6, 0xba, 0xd2, 0x68, 0xf9,
	0xaf, 0x2e, 0x6b, 0x07, 0xb1, 0x36, 0x52, 0x1b, 0x3a, 0x64, 0x06, 0xe8, 0xb8, 0x3b, 0x04, 0xcb,
	0xba, 0x34, 0xd6, 0x42, 0x39, 0x7d, 0x9d, 0x6b, 0xcd, 0x13, 0xa0, 0x2c, 0x15, 0x94, 0x29, 0xa5,
	0x2d, 0xb3, 0x42, 0x2b, 0xe3, 0xd4, 0x4d, 0xd7, 0x9d, 0xa7, 0x3c, 0x63, 0xa3, 0xbf, 0x03, 0xdc,
	0x77, 0x5d, 0x15, 0xad, 0xe1, 0xd5, 0x57, 0x25, 0xd9, 0x73, 0x66, 0xf6, 0x32, 0x11, 0x83, 0xe9,
	0xc3, 0x41, 0x0e, 0xc6, 0x46, 0x5f, 0x11, 0xbe, 0x7d, 0x5e, 0x31, 0xa9, 0x56, 0x06, 0xfc, 0x43,
	0x84, 0xaf, 0x4b, 0xa1, 0x06, 0x9c, 0x99, 0x41, 0x5a, 0x49, 0x2d, 0xb4, 0x71, 0x69, 0x7b, 0x65,
	0x67, 0x9d, 0xd4, 0x3b, 0x49, 0x49, 0x4c, 0xdc, 0x42, 0xf2, 0x14, 0xe2, 0x27, 0x5a, 0xa8, 0xde,
	0xcb, 0xe3, 0xd3, 0xd0, 0xfb, 0x7d, 0x1a, 0xae, 0x16, 0x4c, 0x26, 0xbb, 0xd1, 0xd9, 0x09, 0xd1,
	0x97, 0x1f, 0xe1, 0x23, 0x2e, 0xec, 0x7e, 0x3e, 0x24, 0xb1, 0x96, 0xd4, 0xc1, 0xd7, 0x3f, 0x1d,
	0x33, 0x7a, 0x4b, 0x6d, 0x91, 0x82, 0x69, 0x86, 0x99, 0xfe, 0x35, 0x29, 0xd4, 0x0c, 0x6d, 0x77,
	0xf9, 0xf3, 0x51, 0xe8, 0x45, 0x77, 0xf0, 0x5a, 0x85, 0xfc, 0xba, 0xb6, 0xb8, 0x97, 0x30, 0xd5,
	0xd8, 0x61, 0xb8, 0x75, 0x51, 0x72, 0x7e, 0x9e, 0xe1, 0xe5, 0x34, 0x61, 0xaa, 0x85, 0x36, 0xd0,
	0xbc, 0x89, 0x26, 0xa8, 0xc6, 0x47, 0xd9, 0xd3, 0xbb, 0xe9, 0x4c, 0xac, 0xd4, 0x26, 0xca, 0xbe,
	0xa8, 0x5f, 0xb5, 0xef, 0x1c, 0x2d, 0xe1, 0xcb, 0xd5, 0x0e, 0xff, 0x03, 0xc2, 0x57, 0x67, 0x6c,
	0xfe, 0x7d, 0x72, 0xee, 0xb9, 0xc9, 0xc2, 0xc4, 0xdb, 0x5b, 0xff, 0xac, 0xab, 0x79, 0xa3, 0xad,
	0xf7, 0xdf, 0x7e, 0x7d, 0x5a, 0xba, 0xe7, 0x87, 0x14, 0x3a, 0x52, 0x2b, 0x28, 0xce, 0x5e, 0x1a,
	0x67, 0xa6, 0xce, 0xd4, 0xff, 0x88, 0xf0, 0xca, 0x9c, 0x61, 0x7f, 0x7b, 0xf1, 0x86, 0x8b, 0x71,
	0xb5, 0x1f, 0xfc, 0x47, 0xa5, 0xa3, 0x79, 0x58, 0xd1, 0x6c, 0xfa, 0xd1, 0x62, 0x1a, 0x97, 0xe2,
	0xa0, 0x8c, 0xa8, 0xf7, 0xe2, 0x78, 0x12, 0xa0, 0x93, 0x49, 0x80, 0x7e, 0x4e, 0x02, 0x74, 0x38,
	0x0d, 0xbc, 0x93, 0x69, 0xe0, 0x7d, 0x9f, 0x06, 0xde, 0x1b, 0x32, 0xf7, 0xf6, 0xcd, 0x1c, 0x90,
	0x9d, 0x04, 0x46, 0x1c, 0x32, 0xfa, 0x6e, 0x6e, 0x66, 0x75, 0x07, 0xc3, 0x2b, 0xd5, 0xf9, 0x3e,
	0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x52, 0x20, 0x32, 0x68, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	GasPrices(ctx context.Context, in *QueryGasPricesRequest, opts ...grpc.CallOption) (*QueryGasPricesResponse, error)
	UpgradePlan(ctx context.Context, in *QueryUpgradePlanRequest, opts ...grpc.CallOption) (*QueryUpgradePlanResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GasPrices(ctx context.Context, in *QueryGasPricesRequest, opts ...grpc.CallOption) (*QueryGasPricesResponse, error) {
	out := new(QueryGasPricesResponse)
	err := c.cc.Invoke(ctx, "/em.authority.v1.Query/GasPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UpgradePlan(ctx context.Context, in *QueryUpgradePlanRequest, opts ...grpc.CallOption) (*QueryUpgradePlanResponse, error) {
	out := new(QueryUpgradePlanResponse)
	err := c.cc.Invoke(ctx, "/em.authority.v1.Query/UpgradePlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	GasPrices(context.Context, *QueryGasPricesRequest) (*QueryGasPricesResponse, error)
	UpgradePlan(context.Context, *QueryUpgradePlanRequest) (*QueryUpgradePlanResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GasPrices(ctx context.Context, req *QueryGasPricesRequest) (*QueryGasPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GasPrices not implemented")
}
func (*UnimplementedQueryServer) UpgradePlan(ctx context.Context, req *QueryUpgradePlanRequest) (*QueryUpgradePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradePlan not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GasPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGasPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GasPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/em.authority.v1.Query/GasPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GasPrices(ctx, req.(*QueryGasPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UpgradePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUpgradePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UpgradePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/em.authority.v1.Query/UpgradePlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UpgradePlan(ctx, req.(*QueryUpgradePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "em.authority.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GasPrices",
			Handler:    _Query_GasPrices_Handler,
		},
		{
			MethodName: "UpgradePlan",
			Handler:    _Query_UpgradePlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "em/authority/v1/query.proto",
}

func (m *QueryGasPricesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGasPricesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGasPricesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGasPricesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGasPricesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGasPricesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinGasPrices) > 0 {
		for iNdEx := len(m.MinGasPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinGasPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryUpgradePlanRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUpgradePlanRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUpgradePlanRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryUpgradePlanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUpgradePlanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUpgradePlanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Plan.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGasPricesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGasPricesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MinGasPrices) > 0 {
		for _, e := range m.MinGasPrices {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryUpgradePlanRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryUpgradePlanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Plan.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGasPricesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGasPricesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGasPricesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGasPricesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGasPricesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGasPricesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGasPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinGasPrices = append(m.MinGasPrices, types.DecCoin{})
			if err := m.MinGasPrices[len(m.MinGasPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUpgradePlanRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUpgradePlanRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUpgradePlanRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUpgradePlanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUpgradePlanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUpgradePlanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Plan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
