// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: em/authority/v1beta1/tx.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateIssuerX struct {
	Authority     string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty" yaml:"authority"`
	Issuer        string   `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty" yaml:"issuer"`
	Denominations []string `protobuf:"bytes,3,rep,name=denominations,proto3" json:"denominations,omitempty" yaml:"denoms"`
}

func (m *MsgCreateIssuerX) Reset()         { *m = MsgCreateIssuerX{} }
func (m *MsgCreateIssuerX) String() string { return proto.CompactTextString(m) }
func (*MsgCreateIssuerX) ProtoMessage()    {}
func (*MsgCreateIssuerX) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f2b53ee291f45c, []int{0}
}
func (m *MsgCreateIssuerX) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateIssuerX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateIssuerX.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateIssuerX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateIssuerX.Merge(m, src)
}
func (m *MsgCreateIssuerX) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateIssuerX) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateIssuerX.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateIssuerX proto.InternalMessageInfo

func (m *MsgCreateIssuerX) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgCreateIssuerX) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *MsgCreateIssuerX) GetDenominations() []string {
	if m != nil {
		return m.Denominations
	}
	return nil
}

type MsgDestroyIssuerX struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty" yaml:"authority"`
	Issuer    string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty" yaml:"issuer"`
}

func (m *MsgDestroyIssuerX) Reset()         { *m = MsgDestroyIssuerX{} }
func (m *MsgDestroyIssuerX) String() string { return proto.CompactTextString(m) }
func (*MsgDestroyIssuerX) ProtoMessage()    {}
func (*MsgDestroyIssuerX) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f2b53ee291f45c, []int{1}
}
func (m *MsgDestroyIssuerX) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDestroyIssuerX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDestroyIssuerX.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDestroyIssuerX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDestroyIssuerX.Merge(m, src)
}
func (m *MsgDestroyIssuerX) XXX_Size() int {
	return m.Size()
}
func (m *MsgDestroyIssuerX) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDestroyIssuerX.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDestroyIssuerX proto.InternalMessageInfo

func (m *MsgDestroyIssuerX) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgDestroyIssuerX) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

type MsgSetGasPricesX struct {
	Authority string                                      `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty" yaml:"authority"`
	GasPrices github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,2,rep,name=gas_prices,json=gasPrices,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"gas_prices" yaml:"gas_prices"`
}

func (m *MsgSetGasPricesX) Reset()         { *m = MsgSetGasPricesX{} }
func (m *MsgSetGasPricesX) String() string { return proto.CompactTextString(m) }
func (*MsgSetGasPricesX) ProtoMessage()    {}
func (*MsgSetGasPricesX) Descriptor() ([]byte, []int) {
	return fileDescriptor_11f2b53ee291f45c, []int{2}
}
func (m *MsgSetGasPricesX) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetGasPricesX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetGasPricesX.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetGasPricesX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetGasPricesX.Merge(m, src)
}
func (m *MsgSetGasPricesX) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetGasPricesX) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetGasPricesX.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetGasPricesX proto.InternalMessageInfo

func (m *MsgSetGasPricesX) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetGasPricesX) GetGasPrices() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.GasPrices
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgCreateIssuerX)(nil), "em.authority.v1beta1.MsgCreateIssuerX")
	proto.RegisterType((*MsgDestroyIssuerX)(nil), "em.authority.v1beta1.MsgDestroyIssuerX")
	proto.RegisterType((*MsgSetGasPricesX)(nil), "em.authority.v1beta1.MsgSetGasPricesX")
}

func init() { proto.RegisterFile("em/authority/v1beta1/tx.proto", fileDescriptor_11f2b53ee291f45c) }

var fileDescriptor_11f2b53ee291f45c = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xc1, 0x6a, 0xdb, 0x30,
	0x18, 0xc7, 0xed, 0x06, 0x0a, 0xd1, 0x28, 0x34, 0x26, 0x07, 0x53, 0x36, 0x3b, 0xe8, 0xd4, 0x31,
	0x22, 0xd1, 0xee, 0x30, 0xd8, 0x31, 0x2d, 0xac, 0x3b, 0x14, 0x86, 0x77, 0x19, 0xbb, 0x0c, 0xd9,
	0xf9, 0x50, 0xc5, 0x2a, 0x2b, 0xe8, 0x53, 0x46, 0xfd, 0x00, 0xbb, 0xef, 0x39, 0xf2, 0x24, 0x39,
	0x8d, 0x1c, 0x77, 0xf2, 0x46, 0xf2, 0x06, 0x79, 0x82, 0x11, 0x2b, 0x71, 0x92, 0xeb, 0x0e, 0x3b,
	0xd9, 0xe8, 0xff, 0xff, 0xff, 0xf4, 0xa1, 0xff, 0x47, 0x5e, 0x80, 0xe6, 0x62, 0xea, 0x1e, 0x8c,
	0x55, 0xae, 0xe2, 0xdf, 0xae, 0x72, 0x70, 0xe2, 0x8a, 0xbb, 0x27, 0x36, 0xb1, 0xc6, 0x99, 0xa8,
	0x0f, 0x9a, 0xb5, 0x32, 0xdb, 0xca, 0x17, 0x7d, 0x69, 0xa4, 0x69, 0x0c, 0x7c, 0xf3, 0xe7, 0xbd,
	0x17, 0x49, 0x61, 0x50, 0x1b, 0xe4, 0xb9, 0x40, 0x68, 0x49, 0x85, 0x51, 0xa5, 0xd7, 0xe9, 0x2c,
	0x24, 0xe7, 0xf7, 0x28, 0x6f, 0x2c, 0x08, 0x07, 0xef, 0x11, 0xa7, 0x60, 0x3f, 0x45, 0xd7, 0xa4,
	0xdb, 0xf2, 0xe3, 0x70, 0x10, 0x5e, 0x76, 0x47, 0xfd, 0x75, 0x9d, 0x9e, 0x57, 0x42, 0x3f, 0xbe,
	0xa5, 0xad, 0x44, 0xb3, 0xbd, 0x2d, 0x7a, 0x49, 0x4e, 0x55, 0x13, 0x8f, 0x4f, 0x9a, 0x40, 0x6f,
	0x5d, 0xa7, 0x67, 0x3e, 0xe0, 0xcf, 0x69, 0xb6, 0x35, 0x44, 0x6f, 0xc8, 0xd9, 0x18, 0x4a, 0xa3,
	0x55, 0x29, 0x9c, 0x32, 0x25, 0xc6, 0x9d, 0x41, 0xe7, 0x38, 0xd1, 0xc8, 0x48, 0xb3, 0x63, 0x1f,
	0xb5, 0xa4, 0x77, 0x8f, 0xf2, 0x16, 0xd0, 0x59, 0x53, 0xfd, 0x9f, 0x61, 0xe9, 0x4f, 0xff, 0x40,
	0x1f, 0xc1, 0xbd, 0x13, 0xf8, 0xc1, 0xaa, 0x02, 0xf0, 0xdf, 0xee, 0xfc, 0x1e, 0x12, 0x22, 0x05,
	0x7e, 0x99, 0x34, 0x8c, 0xf8, 0x64, 0xd0, 0xb9, 0x7c, 0x76, 0xfd, 0x9c, 0xf9, 0x7e, 0xd8, 0xa6,
	0x9f, 0x5d, 0x95, 0xec, 0x16, 0x8a, 0x1b, 0xa3, 0xca, 0xd1, 0xdd, 0xbc, 0x4e, 0x83, 0x75, 0x9d,
	0xf6, 0x3c, 0x77, 0x9f, 0xa6, 0xb3, 0xdf, 0xe9, 0x2b, 0xa9, 0xdc, 0xc3, 0x34, 0x67, 0x85, 0xd1,
	0x7c, 0x5b, 0xb2, 0xff, 0x0c, 0x71, 0xfc, 0x95, 0xbb, 0x6a, 0x02, 0xb8, 0x03, 0x61, 0xd6, 0x95,
	0xbb, 0xe1, 0x47, 0x77, 0xf3, 0x65, 0x12, 0x2e, 0x96, 0x49, 0xf8, 0x67, 0x99, 0x84, 0x3f, 0x56,
	0x49, 0xb0, 0x58, 0x25, 0xc1, 0xaf, 0x55, 0x12, 0x7c, 0x66, 0x07, 0x44, 0x18, 0x6a, 0x53, 0x42,
	0xc5, 0x41, 0x0f, 0x1f, 0x61, 0x2c, 0xc1, 0xf2, 0xa7, 0x83, 0x95, 0x6c, 0xe8, 0xf9, 0x69, 0xb3,
	0x42, 0xaf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x45, 0xc0, 0x02, 0xaf, 0x02, 0x00, 0x00,
}

func (m *MsgCreateIssuerX) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateIssuerX) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateIssuerX) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denominations) > 0 {
		for iNdEx := len(m.Denominations) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Denominations[iNdEx])
			copy(dAtA[i:], m.Denominations[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Denominations[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDestroyIssuerX) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDestroyIssuerX) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDestroyIssuerX) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetGasPricesX) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetGasPricesX) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetGasPricesX) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GasPrices) > 0 {
		for iNdEx := len(m.GasPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GasPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateIssuerX) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Denominations) > 0 {
		for _, s := range m.Denominations {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgDestroyIssuerX) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetGasPricesX) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.GasPrices) > 0 {
		for _, e := range m.GasPrices {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateIssuerX) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateIssuerX: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateIssuerX: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denominations", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denominations = append(m.Denominations, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDestroyIssuerX) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDestroyIssuerX: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDestroyIssuerX: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetGasPricesX) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetGasPricesX: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetGasPricesX: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasPrices = append(m.GasPrices, types.DecCoin{})
			if err := m.GasPrices[len(m.GasPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
