#!/bin/zsh

set -ev

# locate emd binary
if [[ -f $PWD/../../build/emd ]]; then
  EMD_NODE=$PWD/.emd
  pushd -q ../../build
  # save absolute path of emd required by cosmovisor
  EMD=$PWD/emd
  popd -q
else
  echo "emd binary not found in $PWD. Please run make to create the emd binary"
  exit 1
fi

$EMD start --home="$EMD_NODE"
