// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: em/market/v1beta1/market.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TimeInForce int32

const (
	TimeInForce_Unspecified       TimeInForce = 0
	TimeInForce_GoodTillCancel    TimeInForce = 1
	TimeInForce_ImmediateOrCancel TimeInForce = 2
	TimeInForce_FillOrKill        TimeInForce = 3
)

var TimeInForce_name = map[int32]string{
	0: "TIME_IN_FORCE_UNSPECIFIED",
	1: "TIME_IN_FORCE_GOOD_TILL_CANCEL",
	2: "TIME_IN_FORCE_IMMEDIATE_OR_CANCEL",
	3: "TIME_IN_FORCE_FILL_OR_KILL",
}

var TimeInForce_value = map[string]int32{
	"TIME_IN_FORCE_UNSPECIFIED":         0,
	"TIME_IN_FORCE_GOOD_TILL_CANCEL":    1,
	"TIME_IN_FORCE_IMMEDIATE_OR_CANCEL": 2,
	"TIME_IN_FORCE_FILL_OR_KILL":        3,
}

func (x TimeInForce) String() string {
	return proto.EnumName(TimeInForce_name, int32(x))
}

func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56f6098fe03b832f, []int{0}
}

type Instrument struct {
	Source      string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (m *Instrument) Reset()         { *m = Instrument{} }
func (m *Instrument) String() string { return proto.CompactTextString(m) }
func (*Instrument) ProtoMessage()    {}
func (*Instrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f6098fe03b832f, []int{0}
}
func (m *Instrument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Instrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Instrument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Instrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instrument.Merge(m, src)
}
func (m *Instrument) XXX_Size() int {
	return m.Size()
}
func (m *Instrument) XXX_DiscardUnknown() {
	xxx_messageInfo_Instrument.DiscardUnknown(m)
}

var xxx_messageInfo_Instrument proto.InternalMessageInfo

func (m *Instrument) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Instrument) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type Order struct {
	ID                uint64                                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty" yaml:"order_id"`
	TimeInForce       TimeInForce                            `protobuf:"varint,2,opt,name=time_in_force,json=timeInForce,proto3,enum=em.market.v1beta1.TimeInForce" json:"time_in_force,omitempty" yaml:"time_in_force"`
	Owner             string                                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	ClientOrderID     string                                 `protobuf:"bytes,4,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty" yaml:"client_order_id"`
	Source            types.Coin                             `protobuf:"bytes,5,opt,name=source,proto3" json:"source" yaml:"source"`
	SourceRemaining   github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,6,opt,name=source_remaining,json=sourceRemaining,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"source_remaining" yaml:"source_remaining"`
	SourceFilled      github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,7,opt,name=source_filled,json=sourceFilled,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"source_filled" yaml:"source_filled"`
	Destination       types.Coin                             `protobuf:"bytes,8,opt,name=destination,proto3" json:"destination" yaml:"destination"`
	DestinationFilled github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,9,opt,name=destination_filled,json=destinationFilled,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"destination_filled" yaml:"destination_filled"`
}

func (m *Order) Reset()      { *m = Order{} }
func (*Order) ProtoMessage() {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f6098fe03b832f, []int{1}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Order.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return m.Size()
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Order) GetTimeInForce() TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return TimeInForce_Unspecified
}

func (m *Order) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Order) GetClientOrderID() string {
	if m != nil {
		return m.ClientOrderID
	}
	return ""
}

func (m *Order) GetSource() types.Coin {
	if m != nil {
		return m.Source
	}
	return types.Coin{}
}

func (m *Order) GetDestination() types.Coin {
	if m != nil {
		return m.Destination
	}
	return types.Coin{}
}

type ExecutionPlan struct {
	Price       github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=price,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"price"`
	FirstOrder  *Order                                 `protobuf:"bytes,2,opt,name=first_order,json=firstOrder,proto3" json:"first_order,omitempty"`
	SecondOrder *Order                                 `protobuf:"bytes,3,opt,name=second_order,json=secondOrder,proto3" json:"second_order,omitempty"`
}

func (m *ExecutionPlan) Reset()      { *m = ExecutionPlan{} }
func (*ExecutionPlan) ProtoMessage() {}
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f6098fe03b832f, []int{2}
}
func (m *ExecutionPlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecutionPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecutionPlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecutionPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionPlan.Merge(m, src)
}
func (m *ExecutionPlan) XXX_Size() int {
	return m.Size()
}
func (m *ExecutionPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionPlan.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionPlan proto.InternalMessageInfo

func (m *ExecutionPlan) GetFirstOrder() *Order {
	if m != nil {
		return m.FirstOrder
	}
	return nil
}

func (m *ExecutionPlan) GetSecondOrder() *Order {
	if m != nil {
		return m.SecondOrder
	}
	return nil
}

type MarketData struct {
	Source      string                                  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination string                                  `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	LastPrice   *github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=last_price,json=lastPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"last_price,omitempty"`
	Timestamp   *time.Time                              `protobuf:"bytes,4,opt,name=timestamp,proto3,stdtime" json:"timestamp,omitempty"`
}

func (m *MarketData) Reset()         { *m = MarketData{} }
func (m *MarketData) String() string { return proto.CompactTextString(m) }
func (*MarketData) ProtoMessage()    {}
func (*MarketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_56f6098fe03b832f, []int{3}
}
func (m *MarketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MarketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MarketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MarketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketData.Merge(m, src)
}
func (m *MarketData) XXX_Size() int {
	return m.Size()
}
func (m *MarketData) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketData.DiscardUnknown(m)
}

var xxx_messageInfo_MarketData proto.InternalMessageInfo

func (m *MarketData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MarketData) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *MarketData) GetTimestamp() *time.Time {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterEnum("em.market.v1beta1.TimeInForce", TimeInForce_name, TimeInForce_value)
	proto.RegisterType((*Instrument)(nil), "em.market.v1beta1.Instrument")
	proto.RegisterType((*Order)(nil), "em.market.v1beta1.Order")
	proto.RegisterType((*ExecutionPlan)(nil), "em.market.v1beta1.ExecutionPlan")
	proto.RegisterType((*MarketData)(nil), "em.market.v1beta1.MarketData")
}

func init() { proto.RegisterFile("em/market/v1beta1/market.proto", fileDescriptor_56f6098fe03b832f) }

var fileDescriptor_56f6098fe03b832f = []byte{
	// 871 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x3f, 0x6f, 0xdb, 0x46,
	0x14, 0x17, 0x6d, 0xd9, 0x89, 0x8f, 0x96, 0x2d, 0x1f, 0x9c, 0x54, 0xe6, 0x40, 0xaa, 0x1c, 0x82,
	0x20, 0x81, 0x49, 0xc4, 0x2d, 0x0a, 0x34, 0x2d, 0x0a, 0x44, 0x12, 0x95, 0x1e, 0x2c, 0x5b, 0x06,
	0xa3, 0xa0, 0x40, 0x51, 0x80, 0xa0, 0xc8, 0x93, 0x7a, 0x30, 0x79, 0x27, 0x90, 0xa7, 0x36, 0xee,
	0x47, 0xf0, 0x94, 0xb1, 0x8b, 0x81, 0x0c, 0x1d, 0xfa, 0x51, 0x32, 0xa6, 0xe8, 0x52, 0x74, 0x60,
	0x0b, 0x79, 0xea, 0xaa, 0x4f, 0x50, 0xf0, 0x8e, 0x92, 0xa5, 0xa6, 0x80, 0xa1, 0x4c, 0xe2, 0x7b,
	0xef, 0xf7, 0x7b, 0xff, 0xee, 0xbd, 0x27, 0xa0, 0xe3, 0xd8, 0x8e, 0xfd, 0xe4, 0x1c, 0x73, 0xfb,
	0x87, 0x27, 0x7d, 0xcc, 0xfd, 0x27, 0x85, 0x68, 0x8d, 0x12, 0xc6, 0x19, 0xdc, 0xc3, 0xb1, 0x55,
	0x28, 0x0a, 0xbb, 0xb6, 0x3f, 0x64, 0x43, 0x26, 0xac, 0x76, 0xfe, 0x25, 0x81, 0x9a, 0x31, 0x64,
	0x6c, 0x18, 0x61, 0x5b, 0x48, 0xfd, 0xf1, 0xc0, 0xe6, 0x24, 0xc6, 0x29, 0xf7, 0xe3, 0x51, 0x01,
	0xd0, 0x03, 0x96, 0xc6, 0x2c, 0xb5, 0xfb, 0x7e, 0x8a, 0xe7, 0xb1, 0x02, 0x46, 0xa8, 0xb4, 0x9b,
	0x6d, 0x00, 0x10, 0x4d, 0x79, 0x32, 0x8e, 0x31, 0xe5, 0xf0, 0x3e, 0xd8, 0x4c, 0xd9, 0x38, 0x09,
	0x70, 0x4d, 0xa9, 0x2b, 0x0f, 0xb7, 0xdc, 0x42, 0x82, 0x75, 0xa0, 0x86, 0x38, 0xe5, 0x84, 0xfa,
	0x9c, 0x30, 0x5a, 0x5b, 0x13, 0xc6, 0x45, 0x95, 0xf9, 0x66, 0x13, 0x6c, 0x74, 0x93, 0x10, 0x27,
	0xf0, 0x53, 0x70, 0x97, 0xe5, 0x1f, 0x1e, 0x09, 0x85, 0x97, 0x72, 0xe3, 0x60, 0x92, 0x19, 0x6b,
	0xa8, 0x35, 0xcd, 0x8c, 0xdd, 0x0b, 0x3f, 0x8e, 0x9e, 0x9a, 0x33, 0xbb, 0xe9, 0xde, 0x11, 0x9f,
	0x28, 0x84, 0xdf, 0x81, 0x4a, 0x9e, 0xba, 0x47, 0xa8, 0x37, 0x60, 0x79, 0x02, 0x79, 0x8c, 0x9d,
	0x23, 0xdd, 0x7a, 0xaf, 0x13, 0x56, 0x8f, 0xc4, 0x18, 0xd1, 0x76, 0x8e, 0x6a, 0xd4, 0xa6, 0x99,
	0xb1, 0x2f, 0x9d, 0x2e, 0xd1, 0x4d, 0x57, 0xe5, 0x37, 0x30, 0xf8, 0x00, 0x6c, 0xb0, 0x1f, 0x29,
	0x4e, 0x6a, 0xeb, 0x79, 0xe6, 0x8d, 0xea, 0x34, 0x33, 0xb6, 0x8b, 0x54, 0x72, 0xb5, 0xe9, 0x4a,
	0x33, 0x7c, 0x01, 0x76, 0x83, 0x88, 0x60, 0xca, 0xbd, 0x79, 0x09, 0x65, 0xc1, 0x78, 0x3c, 0xc9,
	0x8c, 0x4a, 0x53, 0x98, 0x44, 0x95, 0xa2, 0x9a, 0xfb, 0xd2, 0xc5, 0x7f, 0x18, 0xa6, 0x5b, 0x09,
	0x16, 0x80, 0x21, 0xfc, 0x7a, 0xde, 0xd4, 0x8d, 0xba, 0xf2, 0x50, 0x3d, 0x3a, 0xb0, 0xe4, 0x9b,
	0x58, 0xf9, 0x9b, 0xcc, 0xab, 0x6a, 0x32, 0x42, 0x1b, 0xf7, 0xde, 0x66, 0x46, 0x69, 0x9a, 0x19,
	0x15, 0xe9, 0x59, 0xd2, 0xcc, 0xf9, 0x33, 0x70, 0x50, 0x95, 0x5f, 0x5e, 0x82, 0x63, 0x9f, 0x50,
	0x42, 0x87, 0xb5, 0x4d, 0x91, 0x1f, 0xca, 0x89, 0x7f, 0x66, 0xc6, 0x83, 0x21, 0xe1, 0xdf, 0x8f,
	0xfb, 0x56, 0xc0, 0x62, 0xbb, 0x78, 0x79, 0xf9, 0x73, 0x98, 0x86, 0xe7, 0x36, 0xbf, 0x18, 0xe1,
	0xd4, 0x42, 0x94, 0x4f, 0x33, 0xe3, 0xa3, 0xc5, 0x10, 0x37, 0xfe, 0x4c, 0x77, 0x57, 0xaa, 0xdc,
	0x99, 0x06, 0x9e, 0x83, 0x4a, 0x81, 0x1a, 0x90, 0x28, 0xc2, 0x61, 0xed, 0x8e, 0x08, 0xd9, 0x5e,
	0x39, 0xe4, 0xfe, 0x52, 0x48, 0xe9, 0xcc, 0x74, 0xb7, 0xa5, 0xdc, 0x16, 0x22, 0xfc, 0x66, 0x79,
	0xd2, 0xee, 0xde, 0xd6, 0x31, 0xad, 0xe8, 0x18, 0x94, 0xbe, 0x17, 0x47, 0x72, 0x69, 0x40, 0xe1,
	0x4f, 0x00, 0x2e, 0x88, 0xb3, 0x52, 0xb6, 0x44, 0x29, 0xc7, 0x2b, 0x97, 0x72, 0xf0, 0x5e, 0xb8,
	0x79, 0x3d, 0x7b, 0x0b, 0x4a, 0x59, 0xd4, 0xd3, 0xf2, 0xcf, 0x6f, 0x8c, 0x92, 0xf9, 0xbb, 0x02,
	0x2a, 0xce, 0x2b, 0x1c, 0x8c, 0x73, 0xcb, 0x59, 0xe4, 0x53, 0xd8, 0x02, 0x1b, 0xa3, 0x84, 0xcc,
	0xb6, 0xad, 0x61, 0xad, 0x90, 0x46, 0x0b, 0x07, 0xae, 0x24, 0xc3, 0xcf, 0x81, 0x3a, 0x20, 0x49,
	0x5a, 0x4c, 0xa0, 0x58, 0x1c, 0xf5, 0xa8, 0xf6, 0x3f, 0x8b, 0x23, 0x06, 0xd2, 0x05, 0x02, 0x2c,
	0x77, 0xf5, 0x0b, 0xb0, 0x9d, 0xe2, 0x80, 0xd1, 0xb0, 0xe0, 0xae, 0xdf, 0xc2, 0x55, 0x25, 0x5a,
	0x08, 0x45, 0x55, 0xbf, 0x29, 0x00, 0x9c, 0x08, 0x6c, 0xcb, 0xe7, 0xfe, 0x87, 0x5f, 0x10, 0x88,
	0x00, 0x88, 0xfc, 0x94, 0x7b, 0xb2, 0x23, 0x72, 0x51, 0x1f, 0xad, 0xd0, 0x8d, 0xad, 0x9c, 0x7d,
	0x26, 0x3a, 0xf2, 0x15, 0xd8, 0x9a, 0xdf, 0x41, 0xb1, 0xc0, 0xea, 0x91, 0x66, 0xc9, 0x4b, 0x69,
	0xcd, 0x2e, 0xa5, 0x38, 0x23, 0x02, 0xd1, 0x28, 0xbf, 0xfe, 0xcb, 0x50, 0xdc, 0x1b, 0xca, 0xa3,
	0x7f, 0x14, 0xa0, 0x2e, 0x5c, 0x19, 0x68, 0x81, 0x83, 0x1e, 0x3a, 0x71, 0x3c, 0x74, 0xea, 0xb5,
	0xbb, 0x6e, 0xd3, 0xf1, 0x5e, 0x9e, 0xbe, 0x38, 0x73, 0x9a, 0xa8, 0x8d, 0x9c, 0x56, 0xb5, 0xa4,
	0xed, 0x5e, 0x5e, 0xd5, 0xd5, 0x97, 0x34, 0x1d, 0xe1, 0x80, 0x0c, 0x08, 0x0e, 0xe1, 0x67, 0x40,
	0x5f, 0xc6, 0x3f, 0xef, 0x76, 0x5b, 0x5e, 0x0f, 0x75, 0x3a, 0x5e, 0xf3, 0xd9, 0x69, 0xd3, 0xe9,
	0x54, 0x15, 0x0d, 0x5e, 0x5e, 0xd5, 0x77, 0x9e, 0x33, 0x16, 0xf6, 0x48, 0x14, 0x35, 0x7d, 0x1a,
	0xe0, 0x08, 0x7e, 0x09, 0x3e, 0x5e, 0xe6, 0xa1, 0x93, 0x13, 0xa7, 0x85, 0x9e, 0xf5, 0x1c, 0xaf,
	0xeb, 0xce, 0xa8, 0x6b, 0xda, 0xbd, 0xcb, 0xab, 0xfa, 0x1e, 0x8a, 0x63, 0x1c, 0x12, 0x9f, 0xe3,
	0x6e, 0x52, 0xb0, 0x2d, 0xa0, 0x2d, 0xb3, 0xdb, 0x79, 0xc0, 0xae, 0xeb, 0x1d, 0xa3, 0x4e, 0xa7,
	0xba, 0xae, 0xed, 0x5c, 0x5e, 0xd5, 0x41, 0x3e, 0x91, 0xdd, 0xe4, 0x98, 0x44, 0x91, 0x56, 0xfe,
	0xf5, 0x17, 0x5d, 0x69, 0x38, 0x6f, 0x27, 0xba, 0xf2, 0x6e, 0xa2, 0x2b, 0x7f, 0x4f, 0x74, 0xe5,
	0xf5, 0xb5, 0x5e, 0x7a, 0x77, 0xad, 0x97, 0xfe, 0xb8, 0xd6, 0x4b, 0xdf, 0x3e, 0x5e, 0x68, 0x3c,
	0x3e, 0x8c, 0x19, 0xc5, 0x17, 0x36, 0x8e, 0x0f, 0x23, 0x1c, 0x0e, 0x71, 0x62, 0xbf, 0x9a, 0xfd,
	0x81, 0x89, 0x17, 0xe8, 0x6f, 0x8a, 0xbe, 0x7e, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0x71, 0x16, 0x76, 0xda, 0x06, 0x00, 0x00,
}

func (m *Instrument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Instrument) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Instrument) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Destination) > 0 {
		i -= len(m.Destination)
		copy(dAtA[i:], m.Destination)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Destination)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Order) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Order) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Order) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.DestinationFilled.Size()
		i -= size
		if _, err := m.DestinationFilled.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size, err := m.Destination.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.SourceFilled.Size()
		i -= size
		if _, err := m.SourceFilled.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.SourceRemaining.Size()
		i -= size
		if _, err := m.SourceRemaining.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Source.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.ClientOrderID) > 0 {
		i -= len(m.ClientOrderID)
		copy(dAtA[i:], m.ClientOrderID)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.ClientOrderID)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if m.TimeInForce != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.TimeInForce))
		i--
		dAtA[i] = 0x10
	}
	if m.ID != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ExecutionPlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecutionPlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecutionPlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SecondOrder != nil {
		{
			size, err := m.SecondOrder.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMarket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.FirstOrder != nil {
		{
			size, err := m.FirstOrder.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMarket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MarketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MarketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MarketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != nil {
		n5, err5 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.Timestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.Timestamp):])
		if err5 != nil {
			return 0, err5
		}
		i -= n5
		i = encodeVarintMarket(dAtA, i, uint64(n5))
		i--
		dAtA[i] = 0x22
	}
	if m.LastPrice != nil {
		{
			size := m.LastPrice.Size()
			i -= size
			if _, err := m.LastPrice.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintMarket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Destination) > 0 {
		i -= len(m.Destination)
		copy(dAtA[i:], m.Destination)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Destination)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintMarket(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMarket(dAtA []byte, offset int, v uint64) int {
	offset -= sovMarket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Instrument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	l = len(m.Destination)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	return n
}

func (m *Order) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovMarket(uint64(m.ID))
	}
	if m.TimeInForce != 0 {
		n += 1 + sovMarket(uint64(m.TimeInForce))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	l = len(m.ClientOrderID)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	l = m.Source.Size()
	n += 1 + l + sovMarket(uint64(l))
	l = m.SourceRemaining.Size()
	n += 1 + l + sovMarket(uint64(l))
	l = m.SourceFilled.Size()
	n += 1 + l + sovMarket(uint64(l))
	l = m.Destination.Size()
	n += 1 + l + sovMarket(uint64(l))
	l = m.DestinationFilled.Size()
	n += 1 + l + sovMarket(uint64(l))
	return n
}

func (m *ExecutionPlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Price.Size()
	n += 1 + l + sovMarket(uint64(l))
	if m.FirstOrder != nil {
		l = m.FirstOrder.Size()
		n += 1 + l + sovMarket(uint64(l))
	}
	if m.SecondOrder != nil {
		l = m.SecondOrder.Size()
		n += 1 + l + sovMarket(uint64(l))
	}
	return n
}

func (m *MarketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	l = len(m.Destination)
	if l > 0 {
		n += 1 + l + sovMarket(uint64(l))
	}
	if m.LastPrice != nil {
		l = m.LastPrice.Size()
		n += 1 + l + sovMarket(uint64(l))
	}
	if m.Timestamp != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.Timestamp)
		n += 1 + l + sovMarket(uint64(l))
	}
	return n
}

func sovMarket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMarket(x uint64) (n int) {
	return sovMarket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Instrument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Instrument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Instrument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destination = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Order) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Order: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Order: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeInForce", wireType)
			}
			m.TimeInForce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeInForce |= TimeInForce(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientOrderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientOrderID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceRemaining", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SourceRemaining.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceFilled", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SourceFilled.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Destination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationFilled", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DestinationFilled.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionPlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionPlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionPlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstOrder", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FirstOrder == nil {
				m.FirstOrder = &Order{}
			}
			if err := m.FirstOrder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondOrder", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SecondOrder == nil {
				m.SecondOrder = &Order{}
			}
			if err := m.SecondOrder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MarketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MarketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MarketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destination = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.LastPrice = &v
			if err := m.LastPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMarket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMarket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMarket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMarket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMarket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMarket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMarket = fmt.Errorf("proto: unexpected end of group")
)
