#!/bin/bash

set +x

usage() {
  echo "Usage: $0 <hash>"
  echo "Example IBC denomination hash ibc/93FF02E702BE88DE6309464BA7ABCC9932964FA348726B04B06EEE79ECB35768"
  echo "enter -> $0 93FF02E702BE88DE6309464BA7ABCC9932964FA348726B04B06EEE79ECB35768"
  echo "
        denom_trace:
          base_denom: samoleans
          path: transfer/channel-0
  "
  exit 1
}

missing() {
  echo "Missing $1 parameter. Please check if all parameters were specified."
  usage
}

if [ -z "$1" ]; then
  missing "denom-hash"
fi

if [ "$#" -gt 1 ]; then
  echo "Incorrect number of parameters."
  usage
fi

../../build/emd q ibc-transfer denom-trace "$1"