#!/bin/zsh

# Copying test upgrade binary in cosmovisor upgrade folder
# This script is optional and not-needed if exercising the auto
# download option with DAEMON_RESTART_AFTER_UPGRADE=true
# -- or using the http download option as a backup option.

# em-ledger/networks/.emd/cosmovisor
# ├── current -> /home/user/go/src/github.com/e-money/em-ledger/networks/.emd/cosmovisor/genesis/bin/emd
# ├── genesis
# │ └── bin
# │     └── emd
# └── upgrades
#     └── test-upg-0.1.0
#         └── bin
#             └── emd

set -e

UPG_EMD_LOC=/srv/ftp/test-upg-0.1.0

# cosmovisor constants
export DAEMON_NAME=emd

# locate .emd home folder starting either in em-ledger/networks or em-ledger/networks/upg
if [[ -d $PWD/.emd ]]; then
  export DAEMON_HOME=$PWD/.emd
elif [[ -d ../.emd ]]; then
  pushd -q ../
  export DAEMON_HOME=$PWD/.emd
  popd -q
else
  echo ".emd folder not found neither in $PWD nor in parent. run startemd.sh to create node"
  exit 1
fi

echo "node home: $DAEMON_HOME"

COSMOVISOR_UPG_LOC="$DAEMON_HOME"/networks/.emd/cosmovisor/upgrades/test-upg-0.1.0/bin
echo "copying $UPG_EMD_LOC/emd -> $COSMOVISOR_UPG_LOC"

# copy the upgrade binary
mkdir -p "$COSMOVISOR_UPG_LOC"
cp $UPG_EMD_LOC/emd "$COSMOVISOR_UPG_LOC"

echo "copied upgrade binary in $COSMOVISOR_UPG_LOC"

echo "current version: $(cosmovisor version)"