#!/bin/sh

# ensure ../../build/emd is the binary you want to generate the intended sdk
# genesis versioned config files and db and build args i.e. fast-consensus

set -ev

rm -rf .emd

# start emd
./start-full-cv &

# generate ~2 blocks
sleep 5

# stop emd to back it up
killall -q emd

SDK_VERSION=$(../../build/emd version --long | sed -rn 's/cosmos_sdk_version:\s+(\S+)/\1/p')

ZIP_FILE=/tmp/"$SDK_VERSION".zip

zip "$ZIP_FILE" -r .emd

# delete binary files from the zip
zip --delete "$ZIP_FILE" ".emd/cosmovisor/genesis/bin/emd"
zip --delete "$ZIP_FILE" ".emd/cosmovisor/current/bin/emd"
zip --delete "$ZIP_FILE" ".emd/cosmovisor/upgrades/test-upg-0.2.0/bin/emd"

echo created "$ZIP_FILE".