#!/bin/bash
# Run post the upgrade to confirm upgraded values
set -e

EMD=.emd/cosmovisor/current/bin/emd

UPG_PLAN=test-upg-0.2.0

$EMD version # UPG_PLAN

$EMD q authority gas-prices --home=.emd --node tcp://localhost:26657 --chain-id localnet_reuse