#!/bin/bash
# Run post the upgrade to confirm upgraded values
set -e

EMD=.emd/cosmovisor/current/bin/emd

UPG_PLAN="44-upg-test"

if "$EMD" version 2>&1 > /dev/null | grep -q "$UPG_PLAN"; then
    echo 'the v42 to v44 chain upgrade succeeded!'
else
    echo 'the chain upgrade failed!'
    exit 1;
fi