#!/bin/sh

##### em-ledger single node cosmovisor setup
export DAEMON_NAME=emd
export DAEMON_ALLOW_DOWNLOAD_BINARIES=true
export DAEMON_RESTART_AFTER_UPGRADE=true

export DAEMON_HOME=$PWD/.emd

echo "node home: $DAEMON_HOME"

cosmovisor version
