#!/bin/zsh

set -ev

##### em-ledger single node genesis setup

# locate emd binary starting either in em-ledger/networks or em-ledger/networks/utils
if [[ -f $PWD/../../build/emd ]]; then
  pushd ../
  EMD_NODE=$PWD/.emd
  pushd -q ../build
  EMD=$PWD/emd
   # return to networks
  popd -q
elif [[ -f $PWD/../build/emd ]]; then
  EMD_NODE=$PWD/.emd
  pushd -q ../build
  EMD=$PWD/emd
  popd -q
else
  echo "emd binary not found neither in $PWD nor in parent. run make to create binary"
  exit 1
fi

# destructive
# do not do this in production
rm -rf "$EMD_NODE"/config
rm -rf "$EMD_NODE"/data
rm -rf "$EMD_NODE"/keyring-test
# do not delete cosmovisor if it exists

$EMD unsafe-reset-all --home=$EMD_NODE

$EMD init test --chain-id=test --home="$EMD_NODE" --overwrite
$EMD keys add validator --keyring-backend=test --home="$EMD_NODE"
$EMD add-genesis-account "$($EMD keys show validator -a --keyring-backend=test --home="$EMD_NODE")" 1000000000stake,1000000000ungm --home=$EMD_NODE
$EMD gentx validator 500000000stake --keyring-backend=test --home="$EMD_NODE" --chain-id=test

# create genesis emoney1xue7fm6es84jze49grm4slhlmr4ffz8a3u7g3t to set the authority later
AUTH_SEED="fuel public electric luxury short upper quit edge ginger need olive gesture time useful stadium exhaust since team pond wool type flat focus narrow"
(echo "$AUTH_SEED"; echo "$AUTH_SEED") | $EMD keys add authoritykey --recover --keyring-backend=test --home="$EMD_NODE"
AUTHORITY_ADDR=$($EMD keys show authoritykey -a --keyring-backend=test --home="$EMD_NODE")
$EMD add-genesis-account "$AUTHORITY_ADDR" 1000000000000ungm --home=$EMD_NODE

$EMD collect-gentxs --home="$EMD_NODE"

# set the auth address as the chain authority
AUTHORITY_ADDR_VAL=".app_state.authority.key=\"$AUTHORITY_ADDR\""
jq $AUTHORITY_ADDR_VAL < "$EMD_NODE"/config/genesis.json > "$EMD_NODE"/config/tmp_genesis.json
mv "$EMD_NODE"/config/tmp_genesis.json "$EMD_NODE"/config/genesis.json

##### Cosmovisor setup

export DAEMON_NAME=emd
export DAEMON_ALLOW_DOWNLOAD_BINARIES=true
export DAEMON_RESTART_AFTER_UPGRADE=true
export DAEMON_HOME=$EMD_NODE

echo "node home: $DAEMON_HOME"

cosmovisor start --home="$DAEMON_HOME"