#!/bin/sh
# Invoke to schedule an upgrade
# $1 : choose a future block height to upgrade

set -e

EMD=.emd/cosmovisor/current/bin/emd

UPG_PLAN=v44-upg-test

$EMD version
$EMD q authority gas-prices --home=.emd --node tcp://localhost:26657 --chain-id test
$EMD q authority upgrade-plan --home=.emd --node tcp://localhost:26657 --chain-id test

# schedule upgrade
$EMD tx authority schedule-upgrade authoritykey $UPG_PLAN --upgrade-height "$1" --yes --from authoritykey --home=".emd" --node tcp://localhost:26657 --chain-id test --keyring-backend test

# confirm upg plan
$EMD q authority upgrade-plan --home=.emd --node tcp://localhost:26657 --chain-id test