// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: em/liquidityprovider/v1beta1/liquidityprovider.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LiquidityProviderAccount struct {
	Account  *types.Any                               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Mintable github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=mintable,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"mintable" yaml:"mintable"`
}

func (m *LiquidityProviderAccount) Reset()      { *m = LiquidityProviderAccount{} }
func (*LiquidityProviderAccount) ProtoMessage() {}
func (*LiquidityProviderAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e569703434c582b, []int{0}
}
func (m *LiquidityProviderAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityProviderAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityProviderAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityProviderAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityProviderAccount.Merge(m, src)
}
func (m *LiquidityProviderAccount) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityProviderAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityProviderAccount.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityProviderAccount proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LiquidityProviderAccount)(nil), "em.liquidityprovider.v1beta1.LiquidityProviderAccount")
}

func init() {
	proto.RegisterFile("em/liquidityprovider/v1beta1/liquidityprovider.proto", fileDescriptor_9e569703434c582b)
}

var fileDescriptor_9e569703434c582b = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x49, 0xcd, 0xd5, 0xcf,
	0xc9, 0x2c, 0x2c, 0xcd, 0x4c, 0xc9, 0x2c, 0xa9, 0x2c, 0x28, 0xca, 0x2f, 0xcb, 0x4c, 0x49, 0x2d,
	0xd2, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xc4, 0x94, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x92, 0x49, 0xcd, 0xd5, 0xc3, 0x94, 0x83, 0xea, 0x92, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07,
	0x2b, 0xd4, 0x07, 0xb1, 0x20, 0x7a, 0xa4, 0x24, 0x93, 0xf3, 0x8b, 0x73, 0xf3, 0x8b, 0xe3, 0x21,
	0x12, 0x10, 0x0e, 0x54, 0x4a, 0x0e, 0xc2, 0xd3, 0x4f, 0x4a, 0x2c, 0x4e, 0x85, 0xdb, 0x9d, 0x9c,
	0x9f, 0x99, 0x07, 0xd3, 0x9a, 0x9e, 0x9f, 0x9f, 0x9e, 0x93, 0xaa, 0x0f, 0xe6, 0x25, 0x95, 0xa6,
	0xe9, 0x27, 0xe6, 0x55, 0x42, 0xa4, 0x94, 0xde, 0x31, 0x72, 0x49, 0xf8, 0xc0, 0x5c, 0x12, 0x00,
	0x75, 0x89, 0x63, 0x72, 0x72, 0x7e, 0x69, 0x5e, 0x89, 0x90, 0x0d, 0x17, 0x7b, 0x22, 0x84, 0x29,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa2, 0x07, 0x31, 0x49, 0x0f, 0x66, 0x92, 0x9e, 0x63,
	0x5e, 0xa5, 0x13, 0xcf, 0xa9, 0x2d, 0xba, 0x1c, 0x50, 0x3d, 0x9e, 0x41, 0x30, 0x2d, 0x42, 0x55,
	0x5c, 0x1c, 0xb9, 0x99, 0x79, 0x25, 0x89, 0x49, 0x39, 0xa9, 0x12, 0xcc, 0x0a, 0xcc, 0x1a, 0xdc,
	0x46, 0x92, 0x7a, 0x50, 0x67, 0x83, 0x1c, 0x0a, 0xf3, 0xae, 0x9e, 0x73, 0x7e, 0x66, 0x9e, 0x93,
	0xf3, 0x89, 0x7b, 0xf2, 0x0c, 0x9f, 0xee, 0xc9, 0xf3, 0x57, 0x26, 0xe6, 0xe6, 0x58, 0x29, 0xc1,
	0x34, 0x2a, 0xad, 0xba, 0x2f, 0xaf, 0x91, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f,
	0x0b, 0xf5, 0x36, 0x94, 0xd2, 0x2d, 0x4e, 0xc9, 0xd6, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0x06, 0x9b,
	0x51, 0x1c, 0x04, 0xb7, 0xcf, 0x4a, 0xa2, 0x63, 0x81, 0x3c, 0xc3, 0x8c, 0x05, 0xf2, 0x0c, 0x2f,
	0x16, 0xc8, 0x33, 0x5c, 0x42, 0x72, 0x9e, 0x53, 0xc0, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9,
	0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e,
	0xcb, 0x31, 0x44, 0x99, 0x21, 0xd9, 0x93, 0xaa, 0x9b, 0x9b, 0x9f, 0x97, 0x5a, 0xa9, 0x9f, 0x9a,
	0xab, 0x9b, 0x93, 0x9a, 0x92, 0x9e, 0x5a, 0xa4, 0x5f, 0x81, 0x25, 0x9a, 0xc1, 0x76, 0x27, 0xb1,
	0x81, 0x03, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x35, 0x41, 0xc2, 0x0b, 0x02, 0x00,
	0x00,
}

func (m *LiquidityProviderAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityProviderAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityProviderAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Mintable) > 0 {
		for iNdEx := len(m.Mintable) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Mintable[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLiquidityprovider(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Account != nil {
		{
			size, err := m.Account.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLiquidityprovider(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLiquidityprovider(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidityprovider(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidityProviderAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Account != nil {
		l = m.Account.Size()
		n += 1 + l + sovLiquidityprovider(uint64(l))
	}
	if len(m.Mintable) > 0 {
		for _, e := range m.Mintable {
			l = e.Size()
			n += 1 + l + sovLiquidityprovider(uint64(l))
		}
	}
	return n
}

func sovLiquidityprovider(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidityprovider(x uint64) (n int) {
	return sovLiquidityprovider(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidityProviderAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidityprovider
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityProviderAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityProviderAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityprovider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidityprovider
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityprovider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Account == nil {
				m.Account = &types.Any{}
			}
			if err := m.Account.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mintable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidityprovider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidityprovider
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidityprovider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mintable = append(m.Mintable, types1.Coin{})
			if err := m.Mintable[len(m.Mintable)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidityprovider(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidityprovider
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidityprovider(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidityprovider
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidityprovider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidityprovider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidityprovider
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidityprovider
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidityprovider
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidityprovider        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidityprovider          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidityprovider = fmt.Errorf("proto: unexpected end of group")
)
